pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/halcyonmobile/*")
            credentials {
                //username = System.getenv("GITHUB_USERNAME")
                //password = System.getenv("GITHUB_TOKEN")
                username = extra.properties["GITHUB_USERNAME"] as String? ?: System.getenv("GITHUB_USERNAME")
                password = extra.properties["GITHUB_TOKEN"] as String? ?: System.getenv("GITHUB_TOKEN")
            }
        }
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}
rootProject.name = "Mova"
include(":app")
include(":kmm")

include(":kmm:service")
include(":kmm:service:discover")
include(":kmm:service:discover:discover-api")
include(":kmm:service:discover:discover-implementation")
include(":kmm:service:discover:discover-di")
include(":kmm:service:network:network-api")
include(":kmm:service:network:network-implementation")
include(":kmm:service:network:network-di")
include(":kmm:service:auth")
include(":kmm:service:auth:auth-di")
include(":kmm:service:auth:auth-implementation")
include(":kmm:service:content")
include(":kmm:service:content:explore")
include(":kmm:service:content:explore:explore-api")
include(":kmm:service:content:explore:explore-di")
include(":kmm:service:content:explore:explore-implementation")
include(":kmm:service:content:model")
include(":kmm:service:content:model:model-api")
include(":kmm:service:content:model:movie")
include(":kmm:service:content:model:people")
include(":kmm:service:content:tv")
include(":kmm:service:content:model:tv")
include(":kmm:service:content:movie")
include(":kmm:service:content:movie:movie-api")
include(":kmm:service:content:movie:movie-di")
include(":kmm:service:content:movie:movie-implementation")
include(":kmm:service:content:people")
include(":kmm:service:content:people:people-api")
include(":kmm:service:content:people:people-di")
include(":kmm:service:content:people:people-implementation")
include(":kmm:service:content:model:people")
include(":kmm:service:auth:firebase")
include(":kmm:service:auth:firebase:firebase-api")
include(":kmm:service:auth:firebase:firebase-di")
include(":kmm:service:auth:firebase:firebase-implementation")
include(":kmm:service:activityprovider")
include(":kmm:service:activityprovider:activityprovider-api")
include(":kmm:service:activityprovider:activityprovider-api")
include(":kmm:service:activityprovider:activityprovider-implementation")
include(":kmm:service:activityprovider:activityprovider-di")
include(":kmm:service:content:model:genre")
include(":kmm:service:content:genre")
include(":kmm:service:content:genre:genre-api")
include(":kmm:service:content:genre:genre-implementation")
include(":kmm:service:content:genre:genre-di")
include(":kmm:service:content:filter")
include(":kmm:service:content:filter:filter-api")
include(":kmm:service:content:filter:filter-implementation")
include(":kmm:service:content:filter:filter-di")
include(":kmm:service:content:detail")
include(":kmm:service:content:detail:detail-api")
include(":kmm:service:content:detail:detail-implementation")
include(":kmm:service:content:detail:detail-di")
include(":kmm:service:content:model:detail")
include(":kmm:service:content:model:video")
include(":kmm:service:content:model:review")
include(":kmm:service:content:model:cast-crew")
include(":kmm:service:content:video")
include(":kmm:service:content:video:video-api")
include(":kmm:service:content:video:video-implementation")
include(":kmm:service:content:video:video-di")
include(":kmm:service:content:review")
include(":kmm:service:content:review:review-api")
include(":kmm:service:content:model:category")
include(":kmm:service:content:review:review-implementation")
include(":kmm:service:content:review:review-di")
include(":kmm:service:content:cast-crew")
include(":kmm:service:content:cast-crew:cast-crew-api")
include(":kmm:service:content:cast-crew:cast-crew-implementation")
include(":kmm:service:content:cast-crew:cast-crew-di")
include(":kmm:service:content:pagination")

include(":domain")
include(":domain:domain-di")
include(":domain:domain-model")
include(":domain:domain-usecase")
include(":domain:domain-util")

include(":ui")
include(":ui:catalog")
include(":ui:navigation")
include(":ui:theme")
include(":ui:screen")
include(":ui:screen:auth")
include(":ui:screen:auth:login-register")
include(":ui:util")
include(":ui:screen:main")
include(":ui:screen:main:home")
include(":ui:screen:main:explore")
include(":ui:screen:main:profile")
include(":ui:screen:main:favourites")
include(":ui:screen:main:seeall")
include(":ui:screen:main:base")
include(":ui:screen:main:detail")
include(":ui:screen:auth:welcome")

include(":kmm:")
include(":kmm:shared")
include(":kmm:service:network:api")
include(":kmm:service:network:implementation")
include(":kmm:service:content:movie:api")
include(":kmm:service:content:movie:implementation")
include(":kmm:service:content:model:all")
include(":kmm:service:content:pager")
include(":kmm:service:content:cast-crew:api")
include(":kmm:service:content:cast-crew:implementation")
include(":kmm:service:content:detail:api")
include(":kmm:service:content:detail:implementation")
include(":kmm:service:content:explore:api")
include(":kmm:service:content:explore:implementation")
include(":kmm:service:content:filter:api")
include(":kmm:service:content:filter:implementation")
include(":kmm:service:content:genre:api")
include(":kmm:service:content:genre:implementation")
