package com.barabasizsolt.mova.auth.implementation

import com.barabasizsolt.mova.auth.api.IosSimulatorArm64MainAuthenticationService

class IosSimulatorArm64MainAuthenticationServiceImpl : AuthenticationServiceImpl(), IosSimulatorArm64MainAuthenticationService